config/routes.rb
Testapp::Application.routes.draw do

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  namespace :admin do

    resources :home, only: [:index]

    resources :novels
    resources :novel_categories

    root :to => 'home#index'

  end

  root :to => "home#index"

  devise_for :users

  resources :users

  resources :novels

  resources :novel_categories

end

app/models/novel_category.rb
class NovelCategory < ActiveRecord::Base
  attr_accessible :title

  has_and_belongs_to_many :novels

end

app/controllers/admin/novel_categories_controller.rb
class Admin::NovelCategoriesController < Admin::BaseController

  def index
    @categories = NovelCategory.all

    respond_to do |format|
      format.html #index.rss.builder
      format.json { render json: @categories}
    end

  end

  def show
    @category = NovelCategory.find(params[:id])

    respond_to do |format|
      format.html #index.rss.builder
      format.json { render json: @category }
    end
  end

  def new
    @category = NovelCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category}
    end

  end

  def edit
    @category = NovelCategory.find(params[:id])
  end

  def create
    @ategory = NovelCategory.new(params[:novel_category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:admin, @category], notice: 'Categoria cadastrada com sucesso.' }
        format.json { render json: @category, status: :created, location: @category }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @category = NovelCategory.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:novel_category])
        format.html { redirect_to [:admin, @ategory], notice: 'Categoria atualizada com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit"}
        format.json { render json: @category.erros, status: :unprocessable_entity }
      end

    end

  end

  def destroy
    @category = NovelCategory.find(params[:id])
    if @category.destroy
      flash[:notice] = 'Novela excluida com sucesso.'
    else
      flash[:alert] = "Not destroy"
    end

    respond_to do |format|
      format.html { redirect_to admin_novel_categories_url }
      format.json { head :no_content}
    end

  end

end

app/controllers/novel_categories_controller.rb
class NovelCategoriesController < ApplicationController

  def index
    @categories = NovelCategory.all
  end

  def show
    @categories = NovelCategory.find(params[:id], include: [:novels])
  end

end

app/helpers/admin/novel_categories_helper.rb
module Admin::NovelCategoriesHelper
end

app/helpers/novel_categories_helper.rb
module NovelCategoriesHelper
end

app/views/admin/novel_categories/_form.html.erb
<%= form_for([:admin, @category], html: { class: "form-horizontal", :multipart => true}) do |f| %>

    <div class="row">
      <div class="span6 form-left">

        <%= f.label :title, 'Título', class: 'label label-info' %>
        <div class="input">
          <%= f.text_field :title, class: 'span6' %>
        </div>

        <%= f.label :cover, 'Capa', class: 'label label-info' %>
        <div class="input">
          <%= image_tag @category.cover(:thumb), class: 'img-polaroid' unless @category.cover_file_name.blank? %><%= f.file_field :cover %>
        </div>

        <br />
      </div>
    </div>
    <br />

    <div class="well actions">
      <%= f.submit class: 'btn btn-primary', :disable_with => 'Carregando...' %>
      <%=  link_to t(:cancel), :back, class: 'btn btn-danger', :disable_with => 'Carregando...' %>
    </div>

<% end %>

app/views/admin/novel_categories/edit.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to t('activerecord.models.novel_category.many'), admin_novels_path %> <span class="divider">/</span></li>
    <li class="active"><%= translate_action_model('edit', 'novel_category') %></li>
<% end %>

<%= nav_bar_admin('Editar Jogo - ' + @category.title) %>

<%= render 'form' %>

app/views/admin/novel_categories/index.html.erb
<% content_for :breadcrumb do %>
    <li class="active">Categoria de Novelas</li>
<% end %>

<table class="table zebra-striped table-striped table-bordered">
  <thead>
  <tr>
    <th>Título</th>
    <th colspan='3'>Ações</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td class="actions"><i class="icon-hand-up"></i><%= link_to 'Visualizar', [:admin,category] %></td>
        <td class="actions"><i class="icon-edit"></i><%= link_to 'Editar', [:edit,:admin,category] %></td>
        <td class="actions"><i class="icon-remove-sign"></i><%= link_to 'Excluir', [:admin,category], method: 'delete', confirm: 'Confirmar exclusão?' %></td>
      </tr>

  <% end %>
  </tbody>
</table>

<br />

<div id="clear">

</div>

<div class="well actions">
  <%= link_to 'Nova Categoria', new_admin_novel_category_path, :class => "btn btn-success" %>
</div>

app/views/admin/novel_categories/new.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to "Categoria novela", admin_novel_categories_path %> <span class="divider">/</span></li>
<% end %>

<div class="navbar">
  <div class="navbar-inner">
    <div class="brand">
      <li class="active">Nova categoria</li>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/admin/novel_categories/show.html.erb
<% content_for :breadcrumb do %>
    <li><%= link_to t('activerecord.models.novel_category.many'), admin_novel_categories_path %> <span class="divider">/</span></li>
    <li class="active"><%= @category.title %></li>
<% end %>

<%= nav_bar_admin('Detalhes Novela - ' + @category.title) %>

<table class="table table-striped table-bordered table-condensed">

  <tr>
    <th>Título :</th>
    <td><%= @category.title %></td>
  </tr>

  <tr>
    <th>Capa :</th>
    <td><%= image_tag @category.cover(:medium), class: 'img-polaroid' %></td>
  </tr>

</table>
<div class="well actions">
  <%= link_to 'Voltar', :back, class: 'btn', :disable_with => 'Carregando...' %>
  <%= link_to 'Editar', edit_admin_novel_category_path(@category), class: 'btn btn-warning', :disable_with => 'Carregando...' %>
  <%= link_to 'Excluir', admin_novel_category_path(@category), :method => :delete, :confirm => 'Confirmar exclusão?', class: 'btn btn-danger', :disable_with => 'Carregando...' %>
</div>