config/routes.rb
Testapp::Application.routes.draw do

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  namespace :admin do

    resources :home, only: [:index]

    resources :novels
    resources :novel_categories

    root :to => 'home#index'

  end

  root :to => "home#index"

  devise_for :users

  resources :users

  resources :novels

  resources :novel_categories

end

app/models/novel.rb
class Novel < ActiveRecord::Base
  attr_accessible :description, :title, :novel_category_ids

  has_and_belongs_to_many :novel_categories
end

app/controllers/admin/novels_controller.rb
class Admin::NovelsController < Admin::BaseController

  before_filter :category, only: %w(new create edit update)

  def index
    @novels = Novel.all

    respond_to do |format|
      format.html #index.rss.builder
      format.json { render json: @novels}
    end

  end

  def show
    @novel = Novel.find(params[:id])

    respond_to do |format|
      format.html #index.rss.builder
      format.json { render json: @novel }
    end
  end

  def new
    @novel = Novel.new
    @categories = NovelCategory.all


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @novel}
    end

  end

  def edit
    @novel = Novel.find(params[:id])
  end

  def create
    @novel = Novel.new(params[:novel])
    #@category = @novel.novel_categories.build(params[:novel_category])

    respond_to do |format|
      if @novel.save
        format.html { redirect_to [:admin, @novel], notice: 'Novel cadastrada com sucesso.' }
        format.json { render json: @novel, status: :created, location: @novel }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @novel.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    @novel = Novel.find(params[:id])

    respond_to do |format|
      if @novel.update_attributes(params[:novel])
        format.html { redirect_to [:admin, @novel], notice: 'Novela atualizada com sucesso' }
        format.json { head :no_content }
      else
        format.html { render action: "edit"}
        format.json { render json: @novel.erros, status: :unprocessable_entity }
      end

    end

  end

  def destroy
    @novel = Novel.find(params[:id])
    if @novel.destroy
      flash[:notice] = 'Novela excluida com sucesso.'
    else
      flash[:alet] = "Not destroy"
    end

    respond_to do |format|
      format.html { redirect_to admin_novels_url }
      format.json { head :no_content}
    end

  end

  protected

    def category
      @categories = NovelCategory.all
    end

end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController

  def index
    @novels = Novel.all
  end

  def show
    @novel = Novel.find(params[:id])
  end

end

app/helpers/admin/novels_helper.rb
module Admin::NovelsHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/views/admin/novels/_form.html.erb
<%= form_for([:admin, @novel]) do |f| %>

  Titúlo<br />
  <%= f.text_field :title, class: 'span12' %>

  <br />

  Descrição <br />
  <%= f.text_area :description, :rows => "3" %>

  <br />

    <% @categories.each do |category| %>


          <%= label_tag do %>
              <%= radio_button_tag "novel[novel_category_ids][]", category.id, @novel.novel_categories.include?(category) %>
              <%= category.title %> <br />

          <% end %>

    <% end %>

<%= f.submit %>

<% end %>

<%= link_to "Voltar", :back %>

app/views/admin/novels/edit.html.erb
<h2>Editar Novela</h2>

<br />
<br />

<%= render 'form' %>

app/views/admin/novels/index.html.erb
<% content_for :breadcrumb do %>
    <li class="active">Jogos</li>
<% end %>

<table class="table zebra-striped table-striped table-bordered">
  <thead>
  <tr>
    <th>Título</th>
    <th colspan='3'>Ações</th>
  </tr>
  </thead>
  <tbody>
  <% @novels.each do |novel| %>
      <tr>
        <td><%= truncate(novel.title, :length => 115) %></td>
        <td class="actions"><i class="icon-hand-up"></i><%= link_to 'Visualizar', [:admin,novel] %></td>
        <td class="actions"><i class="icon-edit"></i><%= link_to 'Editar', [:edit,:admin,novel] %></td>
        <td class="actions"><i class="icon-remove-sign"></i><%= link_to 'Excluir', [:admin,novel], method: 'delete', confirm: 'Confirmar exclusão?' %></td>
      </tr>

  <% end %>
  </tbody>
</table>

<br />

<div id="clear">

</div>

<div class="well actions">
  <%= link_to 'Nova Novela', new_admin_novel_path, :class => "btn btn-success" %>
</div>

app/views/admin/novels/new.html.erb
<%#= link_to "Novela", admin_novels_path %>


<h2>Nova novela</h2>


<%= render 'form' %>

app/views/admin/novels/show.html.erb
<h2>Visualizando Novela</h2> <br /><br />

<strong>Título :</strong>
<%= @novel.title %>

<br />
<br />

<strong>Descrição :</strong>
<%= @novel.description %>

<br />
<br />

<% @novel.novel_categories.each do |category| %>
   <ul>
      <li><%= category.title %></li>
   </ul>

<% end %>

<%= link_to "Voltar", :back %>